=begin
#TextMagic API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 2

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.8

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TextMagic::GetTimezonesResponse
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'GetTimezonesResponse' do
  before do
    # run before each test
    @instance = TextMagic::GetTimezonesResponse.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GetTimezonesResponse' do
    it 'should create an instance of GetTimezonesResponse' do
      expect(@instance).to be_instance_of(TextMagic::GetTimezonesResponse)
    end
  end
end
