=begin
#TextMagic API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 2

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.8

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TextMagic::GetDisallowedRulesResponse
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'GetDisallowedRulesResponse' do
  before do
    # run before each test
    @instance = TextMagic::GetDisallowedRulesResponse.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GetDisallowedRulesResponse' do
    it 'should create an instance of GetDisallowedRulesResponse' do
      expect(@instance).to be_instance_of(TextMagic::GetDisallowedRulesResponse)
    end
  end
end
