=begin
#TextMagic API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 2

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.8

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TextMagic::UpdateCallbackSettingsInputObject
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'UpdateCallbackSettingsInputObject' do
  before do
    # run before each test
    @instance = TextMagic::UpdateCallbackSettingsInputObject.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UpdateCallbackSettingsInputObject' do
    it 'should create an instance of UpdateCallbackSettingsInputObject' do
      expect(@instance).to be_instance_of(TextMagic::UpdateCallbackSettingsInputObject)
    end
  end
  describe 'test attribute "out_url"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "in_url"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "format"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["m", "u", "j"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.format = value }.not_to raise_error
      # end
    end
  end

end
