=begin
#TextMagic API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 2

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.8

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TextMagic::UpdateSurveyCountryItem
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'UpdateSurveyCountryItem' do
  before do
    # run before each test
    @instance = TextMagic::UpdateSurveyCountryItem.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UpdateSurveyCountryItem' do
    it 'should create an instance of UpdateSurveyCountryItem' do
      expect(@instance).to be_instance_of(TextMagic::UpdateSurveyCountryItem)
    end
  end
  describe 'test attribute "country"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "user_inbound_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
